// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: correo.proto
// Protobuf Java Version: 4.28.3

package com.example.demo;

public final class CorreoProto {
  private CorreoProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      CorreoProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CorreoRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CorreoRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string destinatario = 1;</code>
     * @return The destinatario.
     */
    java.lang.String getDestinatario();
    /**
     * <code>string destinatario = 1;</code>
     * @return The bytes for destinatario.
     */
    com.google.protobuf.ByteString
        getDestinatarioBytes();

    /**
     * <code>string remitente = 2;</code>
     * @return The remitente.
     */
    java.lang.String getRemitente();
    /**
     * <code>string remitente = 2;</code>
     * @return The bytes for remitente.
     */
    com.google.protobuf.ByteString
        getRemitenteBytes();

    /**
     * <code>string asunto = 3;</code>
     * @return The asunto.
     */
    java.lang.String getAsunto();
    /**
     * <code>string asunto = 3;</code>
     * @return The bytes for asunto.
     */
    com.google.protobuf.ByteString
        getAsuntoBytes();

    /**
     * <code>string contenido = 4;</code>
     * @return The contenido.
     */
    java.lang.String getContenido();
    /**
     * <code>string contenido = 4;</code>
     * @return The bytes for contenido.
     */
    com.google.protobuf.ByteString
        getContenidoBytes();
  }
  /**
   * Protobuf type {@code CorreoRequest}
   */
  public static final class CorreoRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CorreoRequest)
      CorreoRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        CorreoRequest.class.getName());
    }
    // Use CorreoRequest.newBuilder() to construct.
    private CorreoRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CorreoRequest() {
      destinatario_ = "";
      remitente_ = "";
      asunto_ = "";
      contenido_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.demo.CorreoProto.internal_static_CorreoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.demo.CorreoProto.internal_static_CorreoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.demo.CorreoProto.CorreoRequest.class, com.example.demo.CorreoProto.CorreoRequest.Builder.class);
    }

    public static final int DESTINATARIO_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object destinatario_ = "";
    /**
     * <code>string destinatario = 1;</code>
     * @return The destinatario.
     */
    @java.lang.Override
    public java.lang.String getDestinatario() {
      java.lang.Object ref = destinatario_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinatario_ = s;
        return s;
      }
    }
    /**
     * <code>string destinatario = 1;</code>
     * @return The bytes for destinatario.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDestinatarioBytes() {
      java.lang.Object ref = destinatario_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinatario_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REMITENTE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object remitente_ = "";
    /**
     * <code>string remitente = 2;</code>
     * @return The remitente.
     */
    @java.lang.Override
    public java.lang.String getRemitente() {
      java.lang.Object ref = remitente_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        remitente_ = s;
        return s;
      }
    }
    /**
     * <code>string remitente = 2;</code>
     * @return The bytes for remitente.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRemitenteBytes() {
      java.lang.Object ref = remitente_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remitente_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ASUNTO_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object asunto_ = "";
    /**
     * <code>string asunto = 3;</code>
     * @return The asunto.
     */
    @java.lang.Override
    public java.lang.String getAsunto() {
      java.lang.Object ref = asunto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        asunto_ = s;
        return s;
      }
    }
    /**
     * <code>string asunto = 3;</code>
     * @return The bytes for asunto.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAsuntoBytes() {
      java.lang.Object ref = asunto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        asunto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENIDO_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object contenido_ = "";
    /**
     * <code>string contenido = 4;</code>
     * @return The contenido.
     */
    @java.lang.Override
    public java.lang.String getContenido() {
      java.lang.Object ref = contenido_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contenido_ = s;
        return s;
      }
    }
    /**
     * <code>string contenido = 4;</code>
     * @return The bytes for contenido.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContenidoBytes() {
      java.lang.Object ref = contenido_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contenido_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(destinatario_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, destinatario_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(remitente_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, remitente_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(asunto_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, asunto_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contenido_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, contenido_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(destinatario_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, destinatario_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(remitente_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, remitente_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(asunto_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, asunto_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contenido_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, contenido_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.demo.CorreoProto.CorreoRequest)) {
        return super.equals(obj);
      }
      com.example.demo.CorreoProto.CorreoRequest other = (com.example.demo.CorreoProto.CorreoRequest) obj;

      if (!getDestinatario()
          .equals(other.getDestinatario())) return false;
      if (!getRemitente()
          .equals(other.getRemitente())) return false;
      if (!getAsunto()
          .equals(other.getAsunto())) return false;
      if (!getContenido()
          .equals(other.getContenido())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DESTINATARIO_FIELD_NUMBER;
      hash = (53 * hash) + getDestinatario().hashCode();
      hash = (37 * hash) + REMITENTE_FIELD_NUMBER;
      hash = (53 * hash) + getRemitente().hashCode();
      hash = (37 * hash) + ASUNTO_FIELD_NUMBER;
      hash = (53 * hash) + getAsunto().hashCode();
      hash = (37 * hash) + CONTENIDO_FIELD_NUMBER;
      hash = (53 * hash) + getContenido().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.demo.CorreoProto.CorreoRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.demo.CorreoProto.CorreoRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.demo.CorreoProto.CorreoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.demo.CorreoProto.CorreoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.demo.CorreoProto.CorreoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.demo.CorreoProto.CorreoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.demo.CorreoProto.CorreoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.demo.CorreoProto.CorreoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.demo.CorreoProto.CorreoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.demo.CorreoProto.CorreoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.demo.CorreoProto.CorreoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.demo.CorreoProto.CorreoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.demo.CorreoProto.CorreoRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CorreoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CorreoRequest)
        com.example.demo.CorreoProto.CorreoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.demo.CorreoProto.internal_static_CorreoRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.demo.CorreoProto.internal_static_CorreoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.demo.CorreoProto.CorreoRequest.class, com.example.demo.CorreoProto.CorreoRequest.Builder.class);
      }

      // Construct using com.example.demo.CorreoProto.CorreoRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        destinatario_ = "";
        remitente_ = "";
        asunto_ = "";
        contenido_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.demo.CorreoProto.internal_static_CorreoRequest_descriptor;
      }

      @java.lang.Override
      public com.example.demo.CorreoProto.CorreoRequest getDefaultInstanceForType() {
        return com.example.demo.CorreoProto.CorreoRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.demo.CorreoProto.CorreoRequest build() {
        com.example.demo.CorreoProto.CorreoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.demo.CorreoProto.CorreoRequest buildPartial() {
        com.example.demo.CorreoProto.CorreoRequest result = new com.example.demo.CorreoProto.CorreoRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.demo.CorreoProto.CorreoRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.destinatario_ = destinatario_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.remitente_ = remitente_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.asunto_ = asunto_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.contenido_ = contenido_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.demo.CorreoProto.CorreoRequest) {
          return mergeFrom((com.example.demo.CorreoProto.CorreoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.demo.CorreoProto.CorreoRequest other) {
        if (other == com.example.demo.CorreoProto.CorreoRequest.getDefaultInstance()) return this;
        if (!other.getDestinatario().isEmpty()) {
          destinatario_ = other.destinatario_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getRemitente().isEmpty()) {
          remitente_ = other.remitente_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getAsunto().isEmpty()) {
          asunto_ = other.asunto_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getContenido().isEmpty()) {
          contenido_ = other.contenido_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                destinatario_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                remitente_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                asunto_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                contenido_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object destinatario_ = "";
      /**
       * <code>string destinatario = 1;</code>
       * @return The destinatario.
       */
      public java.lang.String getDestinatario() {
        java.lang.Object ref = destinatario_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          destinatario_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string destinatario = 1;</code>
       * @return The bytes for destinatario.
       */
      public com.google.protobuf.ByteString
          getDestinatarioBytes() {
        java.lang.Object ref = destinatario_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destinatario_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string destinatario = 1;</code>
       * @param value The destinatario to set.
       * @return This builder for chaining.
       */
      public Builder setDestinatario(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        destinatario_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string destinatario = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDestinatario() {
        destinatario_ = getDefaultInstance().getDestinatario();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string destinatario = 1;</code>
       * @param value The bytes for destinatario to set.
       * @return This builder for chaining.
       */
      public Builder setDestinatarioBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        destinatario_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object remitente_ = "";
      /**
       * <code>string remitente = 2;</code>
       * @return The remitente.
       */
      public java.lang.String getRemitente() {
        java.lang.Object ref = remitente_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          remitente_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string remitente = 2;</code>
       * @return The bytes for remitente.
       */
      public com.google.protobuf.ByteString
          getRemitenteBytes() {
        java.lang.Object ref = remitente_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          remitente_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string remitente = 2;</code>
       * @param value The remitente to set.
       * @return This builder for chaining.
       */
      public Builder setRemitente(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        remitente_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string remitente = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemitente() {
        remitente_ = getDefaultInstance().getRemitente();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string remitente = 2;</code>
       * @param value The bytes for remitente to set.
       * @return This builder for chaining.
       */
      public Builder setRemitenteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        remitente_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object asunto_ = "";
      /**
       * <code>string asunto = 3;</code>
       * @return The asunto.
       */
      public java.lang.String getAsunto() {
        java.lang.Object ref = asunto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          asunto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string asunto = 3;</code>
       * @return The bytes for asunto.
       */
      public com.google.protobuf.ByteString
          getAsuntoBytes() {
        java.lang.Object ref = asunto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          asunto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string asunto = 3;</code>
       * @param value The asunto to set.
       * @return This builder for chaining.
       */
      public Builder setAsunto(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        asunto_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string asunto = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAsunto() {
        asunto_ = getDefaultInstance().getAsunto();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string asunto = 3;</code>
       * @param value The bytes for asunto to set.
       * @return This builder for chaining.
       */
      public Builder setAsuntoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        asunto_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object contenido_ = "";
      /**
       * <code>string contenido = 4;</code>
       * @return The contenido.
       */
      @Override
      public java.lang.String getContenido() {
        java.lang.Object ref = contenido_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contenido_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string contenido = 4;</code>
       * @return The bytes for contenido.
       */
      public com.google.protobuf.ByteString
          getContenidoBytes() {
        java.lang.Object ref = contenido_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contenido_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string contenido = 4;</code>
       * @param value The contenido to set.
       * @return This builder for chaining.
       */
      public Builder setContenido(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        contenido_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string contenido = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearContenido() {
        contenido_ = getDefaultInstance().getContenido();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string contenido = 4;</code>
       * @param value The bytes for contenido to set.
       * @return This builder for chaining.
       */
      public Builder setContenidoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        contenido_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CorreoRequest)
    }

    // @@protoc_insertion_point(class_scope:CorreoRequest)
    private static final com.example.demo.CorreoProto.CorreoRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.demo.CorreoProto.CorreoRequest();
    }

    public static com.example.demo.CorreoProto.CorreoRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CorreoRequest>
        PARSER = new com.google.protobuf.AbstractParser<CorreoRequest>() {
      @java.lang.Override
      public CorreoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CorreoRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CorreoRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.demo.CorreoProto.CorreoRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CorreoResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CorreoResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code CorreoResponse}
   */
  public static final class CorreoResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CorreoResponse)
      CorreoResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        CorreoResponse.class.getName());
    }
    // Use CorreoResponse.newBuilder() to construct.
    private CorreoResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CorreoResponse() {
      message_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.demo.CorreoProto.internal_static_CorreoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.demo.CorreoProto.internal_static_CorreoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.demo.CorreoProto.CorreoResponse.class, com.example.demo.CorreoProto.CorreoResponse.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_ = false;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, message_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.demo.CorreoProto.CorreoResponse)) {
        return super.equals(obj);
      }
      com.example.demo.CorreoProto.CorreoResponse other = (com.example.demo.CorreoProto.CorreoResponse) obj;

      if (getSuccess()
          != other.getSuccess()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.demo.CorreoProto.CorreoResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.demo.CorreoProto.CorreoResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.demo.CorreoProto.CorreoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.demo.CorreoProto.CorreoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.demo.CorreoProto.CorreoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.demo.CorreoProto.CorreoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.demo.CorreoProto.CorreoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.demo.CorreoProto.CorreoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.demo.CorreoProto.CorreoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.demo.CorreoProto.CorreoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.demo.CorreoProto.CorreoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.demo.CorreoProto.CorreoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.demo.CorreoProto.CorreoResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CorreoResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CorreoResponse)
        com.example.demo.CorreoProto.CorreoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.demo.CorreoProto.internal_static_CorreoResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.demo.CorreoProto.internal_static_CorreoResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.demo.CorreoProto.CorreoResponse.class, com.example.demo.CorreoProto.CorreoResponse.Builder.class);
      }

      // Construct using com.example.demo.CorreoProto.CorreoResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        success_ = false;
        message_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.demo.CorreoProto.internal_static_CorreoResponse_descriptor;
      }

      @java.lang.Override
      public com.example.demo.CorreoProto.CorreoResponse getDefaultInstanceForType() {
        return com.example.demo.CorreoProto.CorreoResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.demo.CorreoProto.CorreoResponse build() {
        com.example.demo.CorreoProto.CorreoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.demo.CorreoProto.CorreoResponse buildPartial() {
        com.example.demo.CorreoProto.CorreoResponse result = new com.example.demo.CorreoProto.CorreoResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.demo.CorreoProto.CorreoResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.success_ = success_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.message_ = message_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.demo.CorreoProto.CorreoResponse) {
          return mergeFrom((com.example.demo.CorreoProto.CorreoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.demo.CorreoProto.CorreoResponse other) {
        if (other == com.example.demo.CorreoProto.CorreoResponse.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                success_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {

        success_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CorreoResponse)
    }

    // @@protoc_insertion_point(class_scope:CorreoResponse)
    private static final com.example.demo.CorreoProto.CorreoResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.demo.CorreoProto.CorreoResponse();
    }

    public static com.example.demo.CorreoProto.CorreoResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CorreoResponse>
        PARSER = new com.google.protobuf.AbstractParser<CorreoResponse>() {
      @java.lang.Override
      public CorreoResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CorreoResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CorreoResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.demo.CorreoProto.CorreoResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CorreoRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CorreoRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CorreoResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CorreoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014correo.proto\"[\n\rCorreoRequest\022\024\n\014desti" +
      "natario\030\001 \001(\t\022\021\n\tremitente\030\002 \001(\t\022\016\n\006asun" +
      "to\030\003 \001(\t\022\021\n\tcontenido\030\004 \001(\t\"2\n\016CorreoRes" +
      "ponse\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t2" +
      "v\n\rCorreoService\0221\n\014EnviarCorreo\022\016.Corre" +
      "oRequest\032\017.CorreoResponse\"\000\0222\n\rRecibirCo" +
      "rreo\022\016.CorreoRequest\032\017.CorreoResponse\"\000B" +
      "\037\n\020com.example.demoB\013CorreoProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CorreoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CorreoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CorreoRequest_descriptor,
        new java.lang.String[] { "Destinatario", "Remitente", "Asunto", "Contenido", });
    internal_static_CorreoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CorreoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CorreoResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
